services:
  api:
    build:
      context: ../../services/api-example
      dockerfile: docker/Dockerfile  # Apunta al Dockerfile en la carpeta 'docker'
    command: uvicorn src.main:app --host 0.0.0.0 --port 8050
    expose:
      - "8050"
    #ports:
      - "8050:8050"

    volumes:
      - ../../services/api-example/src:/code/api-example/src
    networks:
      - app-network
    mem_limit: 500m

  backup:
    build:
      context: ../../services/api-example2
      dockerfile: docker/Dockerfile  # Apunta al Dockerfile en la carpeta 'docker'
    command: uvicorn src.main:app --host 0.0.0.0 --port 8050
    expose:
      - "8050"
    volumes:
      - ../../services/api-example2/src:/code/api-example2/src
    networks:
      - app-network
  nginx:
    image: nginx:1
    restart: unless-stopped
    networks:
      - app-network
    mem_limit: 252m
    
    ports:
      - "80:80"    # http
      - "443:443"  # https
    volumes:
      - ../../services/api-gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../services/api-gateway/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../../services/api-gateway/nginx/.htpasswd:/etc/apache2/.htpasswd
      - ../../services/api-gateway/nginx/certificate.pem:/etc/ssl/certs/certificate.pem
      - ../../services/api-gateway/nginx/key.pem:/etc/ssl/certs/key.pem
networks:
  app-network:
    driver: bridge
