version: '3.8'
services:
  api:
    build:
      context: ../../services/api-example
      dockerfile: docker/Dockerfile
    expose:
      - '8050'
    volumes:
      - ../../services/api-example/src:/code/api-example/src
    networks:
      - net
    command: uvicorn src.main:app --host 0.0.0.0 --port 8050
  api2:
    build:
      context: ../../services/api-example2
      dockerfile: docker/Dockerfile
    expose:
      - '8050'
    volumes:
      - ../../services/api-example2/src:/code/api-example2/src
    networks:
      - net
    command: uvicorn src.main:app --host 0.0.0.0 --port 8050
  gateway:
    build:
      context: ../../services/api-gateway/fastapi-gateway
      dockerfile: deployment/Dockerfile
    ports:
      - '80:80'
    networks:
      - net
    command: python3 main.py
networks:
  net:
    driver: bridge
