name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Instalar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Especifica la versión de Python que necesitas

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Establecer el directorio de trabajo
      - name: run docker-compose
        working-directory: ../../infraestructure/docker-compose
        run: docker-compose up --build
      
      # Ejecutar las pruebas
      - name: Run tests
        working-directory: ../../infraestructure/docker-compose
        run: python3 test.py  # Reemplaza con tu servicio y comando de prueba

      # Paso condicional que se ejecuta solo si el script de pruebas fue exitoso
      - name: Do something if tests are successful
        if: ${{ success() }}
        run: echo "Las pruebas fueron exitosas. Continuando con el flujo de trabajo..."

      # Paso condicional que se ejecuta solo si el script de pruebas falló
      - name: Fail the workflow
        if: ${{ failure() }}
        run: echo "Las pruebas fallaron. Abortando el flujo de trabajo."
