name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

     
      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      
      - name: Verificar la ruta y archivos
        run: |
          echo "Directorio actual: $(pwd)"
          ls -R infrastructure/docker-compose


      
      - name: Run Docker in Docker
        uses: docker://docker:latest
        with:
          args: |
            sh -c "
            cd infrastructure/docker-compose && \
            # Construir y ejecutar los servicios
            docker-compose up --build -d
            "
        continue-on-error: false  

      
      - name: Run tests
        run: |
          python3 infrastructure/docker-compose/test.py 
        continue-on-error: false  

      
      - name: Check for success
        if: success()  
        run: echo "El workflow se ejecutó correctamente."

      - name: Check for failure
        if: failure()  
        run: echo "Hubo un error en el workflow."
